---
# tasks file for roles/k8s-postgresql
- tags: [k8s, k8s.postgresql]
  block:
    - name: create backup host path
      ansible.builtin.file:
        path: "{{ k8s_postgresql_backup_host_path }}"
        mode: 0777
        owner: root
        group: root
        state: directory
- tags: [k8s, k8s.postgresql]
  block:
    - name: deploy postgresql helm chart
      community.kubernetes.helm:
        chart_repo_url: https://charts.bitnami.com/bitnami
        chart_ref: postgresql
        chart_version: "{{ k8s_postgresql_version }}"
        release_name: postgresql
        release_namespace: "{{ k8s_postgresql_namespace }}"
        create_namespace: true
        release_state: present
        release_values: "{{ values }}"
    - name: describe deployed statefulset
      community.kubernetes.k8s_info:
        kind: StatefulSet
        namespace: "{{ k8s_postgresql_namespace }}"
        name: postgresql
      register: __info
    - name: get image name
      ansible.builtin.set_fact:
        __image: "{{ __info.resources[0].spec.template.spec.containers[0].image }}"
    - name: deploy backup cron job
      community.kubernetes.k8s:
        resource_definition: "{{ lookup('template', item) }}"
        state: present
      loop: "{{ query('fileglob', role_path + '/templates/k8s/*.yaml.j2') }}"
      loop_control:
        label: "{{ item | basename }}"
  run_once: true
  become: true
