---
values:
  controller:
    ingressClass: "{{ k8s_nginx_name }}"
    setAsDefaultIngress: true
    enableTLSPassthrough: false
    image:
      repository: docker.io/nginx/nginx-ingress
    service:
      create: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "{{ k8s_nginx_external_ip }}"
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
