---
values:
  controller:
    ingressClass: "{{ k8s_nginx_name }}"
    setAsDefaultIngress: true
    enableTLSPassthrough: false
    image:
      repository: docker.io/nginx/nginx-ingress
    service:
      create: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "{{ k8s_nginx_external_ip }}"
    ingressClassResource:
      enabled: true
      name: "{{ k8s_nginx_ingress_class }}"
      default: "{{ k8s_nginx_default }}"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
