---
- tags: [k8s, k8s-metrics-server]
  block:
    - name: install cert-manager helm chart
      kubernetes.core.helm:
        chart_repo_url: https://kubernetes-sigs.github.io/metrics-server
        chart_ref: metrics-server
        chart_version: 3.8.2
        release_namespace: "{{ k8s_metrics_server__namespace }}"
        release_name: "{{ release_name }}"
        release_values: "{{ values }}"
        create_namespace: true
        state: present
      run_once: true
  become: true
