---
- tags: [k8s-prometheus-stack]
  block:
    - name: install kube-prometheus-stack helm chart
      kubernetes.core.helm:
        chart_ref: kube-prometheus-stack
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_version: "{{ k8s_prometheus_stack__chart_version }}"
        release_name: "{{ k8s_prometheus_stack__name }}"
        release_namespace: "{{ k8s_prometheus_stack__namespace }}"
        release_values: "{{ prometheus_stack_values }}"
        create_namespace: true
        state: present
