---
dashboard_enabled: true
helm_enabled: true
registry_enabled: false
metrics_server_enabled: true
csi_snapshot_controller_enabled: true
snapshot_controller_namespace: kube-system
cert_manager_enabled: true
cert_manager_namespace: "cert-manager"
krew_enabled: true
krew_root_dir: "/usr/local/krew"
