---
krew_enabled: true
helm_enabled: true

registry_enabled: false
dashboard_enabled: false
cert_manager_enabled: false
metrics_server_enabled: false
csi_snapshot_controller_enabled: false
snapshot_controller_namespace: kube-system
krew_root_dir: "/usr/local/krew"
