---
- tags: [rclone]
  block:
    - block:
        - name: create download dir
          ansible.builtin.file:
            path: "{{ local_dir }}/rclone"
            mode: 0755
            state: directory
        - name: download rclone package
          ansible.builtin.unarchive:
            src: "https://downloads.rclone.org/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-amd64.zip"
            dest: "{{ local_dir }}/rclone"
            remote_src: true
            creates: "{{ local_dir }}/rclone/rclone-v{{ rclone_version }}-linux-amd64/rclone"
      become: false
      run_once: true
      delegate_to: localhost
    - name: copy rclone package to hosts
      ansible.builtin.copy:
        src: "{{ local_dir }}/rclone/rclone-v{{ rclone_version }}-linux-amd64/rclone"
        dest: /usr/local/bin/rclone
        mode: 0755
        owner: root
        group: root
    - name: copy rclone config
      ansible.builtin.copy:
        content: "{{ rclone_config }}"
        dest: /etc/rclone.conf
        owner: root
        group: root
        mode: 0600
    - name: create rclone backup dir
      ansible.builtin.file:
        path: "{{ rclone_backup_path }}"
        owner: root
        group: root
        mode: 0777
        state: directory
    - name: copy rclone-backup script
      ansible.builtin.template:
        src: rclone-backup.j2
        dest: /usr/local/bin/rclone-backup
        mode: 0700
        owner: root
        group: root
    - name: copy systemd services
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item.rsplit('.', 1)[0] }}"
        mode: 0644
        owner: root
        group: root
      loop:
       - rclone-backup.service.j2
       - rclone-backup.timer.j2
    - name: enable rclone-backup timer
      ansible.builtin.systemd:
        name: rclone-backup.timer
        enabled: true
        daemon_reload: true
        state: started
  rescue:
    - name: remove temporary dir
      ansible.builtin.file:
        path: "{{ local_dir }}/rclone"
        state: absent
      become: false
      run_once: true
      delegate_to: localhost
  become: true
