---
- tags: [k8s, k8s.transmission]
  block:
    - name: download helm chart
      ansible.builtin.get_url:
        url: https://github.com/k8s-at-home/charts/releases/download/transmission-8.4.3/transmission-8.4.3.tgz
        dest: &p /tmp/transmission.chart.tgz
        mode: 0644
        owner: root
        group: root
    - name: create transmission host directories
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 0777
        owner: root
        group: root
        state: directory
      loop:
        - "{{ k8s_transmission__download_dir }}"
        - "{{ k8s_transmission__watch_dir }}"
        - "{{ k8s_transmission__incomplete_dir }}"
    - name: install transmission helm chart
      kubernetes.core.helm:
        chart_ref: *p
        release_namespace: "{{ k8s_transmission__namespace }}"
        release_name: "{{ release_name }}"
        release_values: "{{ values }}"
        create_namespace: true
        atomic: true
        state: present
      run_once: true
  always:
    - name: remove helm chart
      ansible.builtin.file:
        path: *p
        state: absent
  become: true
