---
- tags: [k8s, k8s.metallb]
  block:
    - name: install metallb
      kubernetes.core.helm:
        release_name: "{{ k8s_metallb_name }}"
        release_namespace: "{{ k8s_metallb_namespace }}"
        release_state: present
        release_values: "{{ values }}"
        chart_repo_url: https://metallb.github.io/metallb
        chart_ref: metallb
        chart_version: '0.12.1'
        create_namespace: true
