---
- hosts: all
  become: false
  gather_facts: false
  any_errors_fatal: true
  strategy: free
  tasks:
    - block:
        - name: create local dir
          file:
            path: "{{ local_dir }}"
            mode: 0700
            state: directory
        - name: decrypt ansible private key
          copy:
            content: "{{ sops.connect.ansible_ssh_private_key }}"
            dest: "{{ ansible_private_key_file }}"
            mode: 0600
      delegate_to: localhost
