---
- tags: [connect, always]
  ansible.builtin.import_playbook: connect.main.yaml
- tags: [bootstrap]
  ansible.builtin.import_playbook: bootstrap.main.yaml
- tags: [k8s]
  ansible.builtin.import_playbook: k8s.main.yaml
- tags: [k8s, k8s.platform]
  ansible.builtin.import_playbook: k8s-platform.main.yaml
- tags: [k8s, k8s.apps]
  ansible.builtin.import_playbook: k8s-apps.main.yaml
