---
values:
  image:
    repository: docker.io/rancher/local-path-provisioner
  helperImage:
    repository: docker.io/busybox
  storageClass:
    create: true
    defaultClass: "{{ k8s_lpp_sc_default | bool }}"
    name: "{{ k8s_lpp_sc_name }}"
    reclaimPolicy: Delete
  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - "{{ k8s_lpp_host_path }}"
