---
- tags: [k8s, k8s.cert-manager]
  block:
    - name: download helm chart
      ansible.builtin.get_url:
        url: https://charts.jetstack.io/charts/cert-manager-v1.8.0.tgz
        dest: /tmp/cert-manager.tgz
        mode: 0644
        owner: root
        group: root
    - name: install cert-manager helm chart
      kubernetes.core.helm:
        chart_ref: /tmp/cert-manager.tgz
        release_namespace: "{{ k8s_cert_manager__namespace }}"
        release_name: "{{ release_name }}"
        release_values: "{{ values }}"
        create_namespace: true
        atomic: true
        state: present
  always:
    - name: remove helm chart
      ansible.builtin.file:
        path: /tmp/cert-manager.tgz
        state: absent
  become: true
  run_once: true
