---
- tags: [k8s, k8s-cert-manager]
  block:
    - name: install cert-manager helm chart
      kubernetes.core.helm:
        chart_repo_url: https://charts.jetstack.io
        chart_ref: cert-manager
        chart_version: v1.8.0
        release_namespace: "{{ k8s_cert_manager__namespace }}"
        release_name: "{{ release_name }}"
        release_values: "{{ values }}"
        create_namespace: true
        state: present
      run_once: true
  become: true
