---
values:
  global:
    imageRegistry: docker.io
    storageClass: "{{ k8s_postgresql_data_sc }}"
    postgresPassword: "{{ k8s_postgresql_password }}"
  auth:
    enablePostgreUser: true
    database: postgres
  primary:
    service:
      type: LoadBalancer
      loadBalancerIP: "{{ k8s_postgresql_load_balancer_ip }}"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
