---
- tags: [unbound-dns]
  block:
    - name: check constraints
      ansible.builtin.assert:
        that:
          - unbound__local_domain is defined and unbound__local_domain | length > 0
          - unbound__local_ip is defined and unbound__local_ip | length > 0
    - name: gather facts
      ansible.builtin.setup:
        filter:
          - ansible_default_ipv4
          - ansible_processor_vcpus
    - name: install unbound dns
      ansible.builtin.apt:
        name: unbound
        state: present
    - name: configure unbound forwarding
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ [config_dir, item | basename | splitext | first] | join('/') }}"
        mode: 0600
        owner: root
        group: root
      loop: "{{ query('fileglob', role_path + '/templates/*.conf.j2') }}"
      notify:
        - reload unbound
    - name: create drop-in directory
      ansible.builtin.file:
        path: /etc/systemd/system/unbound.service.d
        mode: 0755
        owner: root
        group: root
        state: directory
    - name: configure unbound service
      ansible.builtin.copy:
        dest: /etc/systemd/system/unbound.service.d/10-after.conf
        content: |-
          [Unit]
          After=network-online.target
        mode: 0644
        owner: root
        group: root
      notify:
        - reload unbound
    - name: enable unbound
      ansible.builtin.systemd:
        name: unbound.service
        enabled: true
        state: started
    - name: flush handlers
      ansible.builtin.meta: flush_handlers
