---
k8s_le__email: "grassoner@gmail.com"
k8s_le__server: https://acme-staging-v02.api.letsencrypt.org/directory
k8s_le__cloudflare_api_token: "UIwxp1jQ9K0LvbaRUaQwp4IOIzf-WpBX1mHWLD4O"
k8s_le__cloudflare_email: "grassoner@gmail.com"
k8s_le__ingress_class: "{{ ingress_external_class }}"
