---
k8s_syncthing__namespace: syncthing
k8s_syncthing__ingress_class: "{{ ingress_internal_class }}"
k8s_syncthing__ingress_host: "syncthing.{{ internal_domain }}"
k8s_syncthing__storage_class: ssd
k8s_syncthing__ingress_annotations:
  cert-manager.io/cluster-issuer: "{{ k8s_le__cluster_issuer }}"
