---
apiVersion: v1
kind: Namespace
metadata:
  name: frp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: frp
data:
  "client.toml": |-
    serverAddr = "192.168.88.252"
    serverPort = 7000

    [[proxies]]
    name = "ingress"
    type = "http"
    localIP = "192.168.88.90"
    localPort = 80
    customDomains = [ "auth.iverian.ru" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc
  namespace: frp
spec:
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
        - name: frpc
          image: gists/frp:0.66.0
          command:
            - frpc
            - -c
            - /config/client.toml
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: config
